"""STRUCT-C2A candidate intent vs spread expression loop statuses."""

from __future__ import annotations

from enum import Enum


class CandidateLoopStatus(str, Enum):
    SG_ACCEPTED = "SG_ACCEPTED"
    HYDRATION_PENDING = "HYDRATION_PENDING"
    HYDRATED = "HYDRATED"
    PARTIAL_HYDRATION = "PARTIAL_HYDRATION"
    EXPRESSION_SEARCH = "EXPRESSION_SEARCH"
    PRIMARY_EXPRESSION_SELECTED = "PRIMARY_EXPRESSION_SELECTED"
    WATCH_EXPRESSION_AVAILABLE = "WATCH_EXPRESSION_AVAILABLE"
    WATCH_OPERATOR_REVIEW = "WATCH_OPERATOR_REVIEW"
    WATCH_OPERATOR_APPROVED = "WATCH_OPERATOR_APPROVED"
    WATCH_OPERATOR_REJECTED = "WATCH_OPERATOR_REJECTED"
    ALTERNATES_AVAILABLE = "ALTERNATES_AVAILABLE"
    NO_VIABLE_EXPRESSION = "NO_VIABLE_EXPRESSION"
    PARKED_DATA_GAP = "PARKED_DATA_GAP"
    PARKED_REVIEW = "PARKED_REVIEW"


class HydrationStatus(str, Enum):
    HYDRATED = "HYDRATED"
    PARTIAL_HYDRATION = "PARTIAL_HYDRATION"
    REQUERY_REQUIRED = "REQUERY_REQUIRED"
    NO_CHAIN_AVAILABLE = "NO_CHAIN_AVAILABLE"
    NO_VIABLE_EXPRESSION = "NO_VIABLE_EXPRESSION"
    PARKED_DATA_GAP = "PARKED_DATA_GAP"


class SpreadExpressionStatus(str, Enum):
    PRIMARY = "PRIMARY"
    ALTERNATE = "ALTERNATE"
    WATCH = "WATCH"
    OPERATOR_APPROVED_WATCH = "OPERATOR_APPROVED_WATCH"
    OPERATOR_REJECTED_WATCH = "OPERATOR_REJECTED_WATCH"
    FAILED_EXPRESSION = "FAILED_EXPRESSION"


class PaperRouteStatus(str, Enum):
    NOT_ROUTED = "NOT_ROUTED"
    PAPER_REVIEW_READY = "PAPER_REVIEW_READY"
    PAPER_APPROVED = "PAPER_APPROVED"
    PAPER_SUBMITTED = "PAPER_SUBMITTED"
